using UnityEngine;
using System.Collections;

namespace Arteficer
{
    public enum OneHundredSprites
    {
          apple_green
        , apple_red
        , orange
        , lime
        , lemon
        , strawberry
        , grapes_red
        , grapes_green
        , blackberry
        , melon
        , bananas
        , orange_cut
        , lime_cut
        , lemon_cut
        , melon_cut
        , kiwifruit_cut
        , tomato
        , pepper_green
        , pepper_yellow
        , pepper_red
        , potato
        , mushroom
        , mushroom_red
        , cheese
        , bread
        , sandwhich
        , egg
        , egg_spotted
        , egg_fried
        , pretzel
        , pizza
        , cookie
        , cupcake
        , cake_sponge
        , cake_chocolate
        , doughnut
        , doughnut_pink
        , muffin
        , marshmallow_pink
        , marshmallow_white
        , icepop_orange
        , icepop_chocolate
        , icepop_redwhiteblue
        , sweet_pink
        , sweet_blue
        , sweet_yellow
        , lollypop
        , candycane
        , hotchocolate
        , soda
        , flower_white
        , flower_red
        , bowlingball
        , beachball
        , football
        , basketball
        , tennisball
        , eightball
        , thirteenball
        , baseball
        , american_football
        , pingpongbat
        , bowlingpin
        , boot
        , glove_blue
        , glove_pink
        , shades
        , tophat
        , fez
        , baseballcap
        , leprechaunhat
        , wollyhat
        , propellerhat
        , minershat
        , sunhat
        , cowboyhat
        , sledgehammer
        , clawhammer
        , spanner
        , saw
        , pliers
        , gear
        , spoon
        , fork
        , knife
        , present
        , rubixcube
        , dice
        , earth
        , saturn
        , moon
        , crystal_blue
        , crystal_pink
        , crystal_green
        , cloud
        , shamrock
        , star
        , heart
        , musicalnote
        , musicalnote_two
    }
}
